# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a02fa50b4f32aa32d32f5c7998fbae17fc6eadef6161543a9d83364006b41b6d9a1b02199f77b6c3fb7f60e4890745714172895562efcb628ca924e3fe2ec8f

test:
  secret_key_base: 0a28868d20061954acd1e2e31a5580693b025dbe3378b5ef9b81ebf566495c154a7542ca27694f2786ffb8a126882b8b243e70869a815b24cfee5bc972cc751b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
